---
brightness: auto
colors:
- - '255'
  - '0'
  - '0'
- - '255'
  - '0'
  - '0'
- - '255'
  - '255'
  - '0'
- - '0'
  - '255'
  - '0'
- - '0'
  - '255'
  - '0'
- - '0'
  - '255'
  - '255'
- - '0'
  - '0'
  - '255'
- - '0'
  - '0'
  - '255'
theme: custom
analog:
  - condensator: 0.047
  - resistor: 5000
